resolver: lts-21.25

# User package locations
packages:
  - .

# Dependency packages to be pulled from upstream that are not in the resolver
# Override the default (latest LTS) with a specific GHC version
# compiler: ghc-9.4.8

# Extra package databases
# extra-deps:
#   - some-package-0.1.0

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of Stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.9"
#
# Override the architecture used by Stack, useful for architectures
# other than the default of the host system (e.g., to force cross-compiling)
# arch: i386
# arch: x86_64
#
# Extra directories used by Stack for building packages
# extra-include-dirs: [/path/to/include]
# extra-lib-dirs: [/path/to/lib]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
